use_frameworks!

platform :ios, '11.0'

#use_modular_headers!
#use_frameworks!

target 'HSKit_Example' do
  pod 'HSKit', :path => '../'

  target 'HSKit_Tests' do
    inherit! :search_paths

#    pod 'YYText' :modular_headers => true
#    pod 'YYModel' :modular_headers => true
    
  end
end

pre_install do |installer|
Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
