use_frameworks!

platform :ios, '11.0'

target 'HSKit_Example' do
  pod 'HSKit', :path => '../'

  target 'HSKit_Tests' do
    inherit! :search_paths

    pod 'YYText', :git => 'git@github.com:fuchenxi/YYText.git'
    
  end
end
